{
  "repository": {
    "name": "traneio/ndbc",
    "githubId": 84398452,
    "url": "https://github.com/traneio/ndbc",
    "isFork": false,
    "original": {
      "name": "",
      "githubId": 0,
      "url": ""
    },
    "isPullRequest": false,
    "pullRequestId": 0
  },
  "builds": {
    "buggyBuild": {
      "id": 425426170,
      "url": "http://travis-ci.org/traneio/ndbc/builds/425426170",
      "date": "Sep 6, 2018 9:44:12 PM"
    }
  },
  "projectMetrics": {
    "numberModules": 8,
    "numberSourceFiles": 186,
    "numberTestFiles": 56,
    "numberLibrariesFailingModule": 10
  },
  "tests": {
    "failingModule": "/root/workspace/traneio/ndbc/425426170/ndbc-postgres-netty4",
    "overallMetrics": {
      "numberRunning": 299,
      "numberPassing": 242,
      "numberFailing": 0,
      "numberErroring": 57,
      "numberSkipping": 0,
      "failures": [
        {
          "failureName": "io.trane.future.CheckedFutureException",
          "isError": true,
          "occurrences": 57
        }
      ]
    },
    "failingClasses": [
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "numberRunning": 30,
        "numberPassing": 0,
        "numberFailing": 0,
        "numberErroring": 30,
        "numberSkipping": 0
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "numberRunning": 14,
        "numberPassing": 0,
        "numberFailing": 0,
        "numberErroring": 14,
        "numberSkipping": 0
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "numberRunning": 13,
        "numberPassing": 0,
        "numberFailing": 0,
        "numberErroring": 13,
        "numberSkipping": 0
      }
    ],
    "failureDetails": [
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "floatArray",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleExecuteDeleteFailure",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "integer",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "double_",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "longArray",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "float_",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "byte_",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleQuery",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedQueryNoParams",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteUpdateNoParamFailure",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteInsertNoParamFailure",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteDeleteWithParamFailure",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "byteArrayArray",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "shortArray",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleExecuteInsertFailure",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "cancellation",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteUpdteWithParamFailure",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleExecuteInsert",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "transactionLocalFailure",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleQueryFailure",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "transactionSuccess",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleExecuteUpdateFailure",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "localTimeArray",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "long_",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedQueryInvalid",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "offsetTime",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "localDateTimeArray",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteUpdateWithParam",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedQueryWithParamsFailure",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleExecuteDelete",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "localTime",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "offsetTimeArray",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "string",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "short_",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "booleanArray",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleQueryInvalid",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "byteArray",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteInsertNoParam",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteInsertWithParamFailure",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleExecuteUpdate",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "integerArray",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteDeleteNoParamFailure",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "stringArray",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedQueryNoParamsFailure",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "bigDecimalArray",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "_boolean",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteUpdateNoParam",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteDeleteWithParam",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "localDateTime",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "localDate",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "transactionDBFailure",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteDeleteNoParam",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteInsertWithParam",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "doubleArray",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "bigDecimal",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "localDateArray",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedQueryWithParams",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      }
    ]
  },
  "reproductionBuggyBuild": {
    "reproductionDateBeginning": "Sep 6, 2018 10:05:56 PM",
    "reproductionDateEnd": "Sep 6, 2018 10:09:19 PM",
    "totalDuration": 200,
    "processDurations": {
      "cloning": {
        "nbSteps": 1,
        "totalDuration": 4,
        "stepNames": [
          "CloneRepository"
        ],
        "stepDurations": [
          4
        ]
      },
      "building": {
        "nbSteps": 2,
        "totalDuration": 18,
        "stepNames": [
          "CheckoutBuggyBuild",
          "BuildProject"
        ],
        "stepDurations": [
          0,
          18
        ]
      },
      "testing": {
        "nbSteps": 1,
        "totalDuration": 15,
        "stepNames": [
          "TestProject"
        ],
        "stepDurations": [
          15
        ]
      }
    },
    "projectRootPomPath": "./workspace/traneio/ndbc/425426170/pom.xml"
  },
  "patchDiff": {
    "files": {
      "numberAdded": 0,
      "numberChanged": 0,
      "numberDeleted": 0
    },
    "lines": {
      "numberAdded": 0,
      "numberDeleted": 0
    }
  },
  "commits": {
    "buggyBuild": {
      "repoName": "traneio/ndbc",
      "branchName": "enconding-arrays",
      "sha": "dd558981cbca64f1152c3ec93f54ee83e080fc9d",
      "url": "http://github.com/traneio/ndbc/commit/dd558981cbca64f1152c3ec93f54ee83e080fc9d",
      "date": "Sep 6, 2018 9:38:37 PM"
    }
  },
  "type": "only_fail"
}