{
  "tests": {
    "failingModule": "/root/workspace/aleksvv/spring-otus/423184096/library",
    "overallMetrics": {
      "numberRunning": 13,
      "numberPassing": 2,
      "numberFailing": 0,
      "numberErroring": 11,
      "numberSkipping": 0,
      "failures": [
        {
          "failureName": "org.springframework.dao.DataAccessResourceFailureException",
          "isError": true,
          "occurrences": 11
        }
      ]
    },
    "failingClasses": [
      {
        "testClass": "ru.vorotov.library.service.BookServiceTest",
        "numberRunning": 2,
        "numberPassing": 0,
        "numberFailing": 0,
        "numberErroring": 2,
        "numberSkipping": 0
      },
      {
        "testClass": "ru.vorotov.library.dao.data.DataJpaAuthorRepositoryTest",
        "numberRunning": 4,
        "numberPassing": 0,
        "numberFailing": 0,
        "numberErroring": 4,
        "numberSkipping": 0
      },
      {
        "testClass": "ru.vorotov.library.dao.data.DataJpaGenreRepositoryTest",
        "numberRunning": 4,
        "numberPassing": 0,
        "numberFailing": 0,
        "numberErroring": 4,
        "numberSkipping": 0
      },
      {
        "testClass": "ru.vorotov.library.dao.data.DataJpaBookRepositoryTestTest",
        "numberRunning": 1,
        "numberPassing": 0,
        "numberFailing": 0,
        "numberErroring": 1,
        "numberSkipping": 0
      }
    ],
    "failureDetails": [
      {
        "testClass": "ru.vorotov.library.dao.data.DataJpaAuthorRepositoryTest",
        "testMethod": "testGet",
        "failureName": "org.springframework.dao.DataAccessResourceFailureException",
        "detail": "Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type\u003dUNKNOWN, servers\u003d[{address\u003dlocalhost:27017, type\u003dUNKNOWN, state\u003dCONNECTING, exception\u003d{com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type\u003dUNKNOWN, servers\u003d[{address\u003dlocalhost:27017, type\u003dUNKNOWN, state\u003dCONNECTING, exception\u003d{com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]",
        "isError": true
      },
      {
        "testClass": "ru.vorotov.library.dao.data.DataJpaAuthorRepositoryTest",
        "testMethod": "testSave",
        "failureName": "org.springframework.dao.DataAccessResourceFailureException",
        "detail": "Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type\u003dUNKNOWN, servers\u003d[{address\u003dlocalhost:27017, type\u003dUNKNOWN, state\u003dCONNECTING, exception\u003d{com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type\u003dUNKNOWN, servers\u003d[{address\u003dlocalhost:27017, type\u003dUNKNOWN, state\u003dCONNECTING, exception\u003d{com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]",
        "isError": true
      },
      {
        "testClass": "ru.vorotov.library.service.BookServiceTest",
        "testMethod": "saveBook",
        "failureName": "org.springframework.dao.DataAccessResourceFailureException",
        "detail": "Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type\u003dUNKNOWN, servers\u003d[{address\u003dlocalhost:27017, type\u003dUNKNOWN, state\u003dCONNECTING, exception\u003d{com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type\u003dUNKNOWN, servers\u003d[{address\u003dlocalhost:27017, type\u003dUNKNOWN, state\u003dCONNECTING, exception\u003d{com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]",
        "isError": true
      },
      {
        "testClass": "ru.vorotov.library.dao.data.DataJpaBookRepositoryTestTest",
        "testMethod": "testGet",
        "failureName": "org.springframework.dao.DataAccessResourceFailureException",
        "detail": "Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type\u003dUNKNOWN, servers\u003d[{address\u003dlocalhost:27017, type\u003dUNKNOWN, state\u003dCONNECTING, exception\u003d{com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type\u003dUNKNOWN, servers\u003d[{address\u003dlocalhost:27017, type\u003dUNKNOWN, state\u003dCONNECTING, exception\u003d{com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]",
        "isError": true
      },
      {
        "testClass": "ru.vorotov.library.dao.data.DataJpaGenreRepositoryTest",
        "testMethod": "testDelete",
        "failureName": "org.springframework.dao.DataAccessResourceFailureException",
        "detail": "Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type\u003dUNKNOWN, servers\u003d[{address\u003dlocalhost:27017, type\u003dUNKNOWN, state\u003dCONNECTING, exception\u003d{com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type\u003dUNKNOWN, servers\u003d[{address\u003dlocalhost:27017, type\u003dUNKNOWN, state\u003dCONNECTING, exception\u003d{com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]",
        "isError": true
      },
      {
        "testClass": "ru.vorotov.library.service.BookServiceTest",
        "testMethod": "testGet",
        "failureName": "org.springframework.dao.DataAccessResourceFailureException",
        "detail": "Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type\u003dUNKNOWN, servers\u003d[{address\u003dlocalhost:27017, type\u003dUNKNOWN, state\u003dCONNECTING, exception\u003d{com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type\u003dUNKNOWN, servers\u003d[{address\u003dlocalhost:27017, type\u003dUNKNOWN, state\u003dCONNECTING, exception\u003d{com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]",
        "isError": true
      },
      {
        "testClass": "ru.vorotov.library.dao.data.DataJpaGenreRepositoryTest",
        "testMethod": "testGetAll",
        "failureName": "org.springframework.dao.DataAccessResourceFailureException",
        "detail": "Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type\u003dUNKNOWN, servers\u003d[{address\u003dlocalhost:27017, type\u003dUNKNOWN, state\u003dCONNECTING, exception\u003d{com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type\u003dUNKNOWN, servers\u003d[{address\u003dlocalhost:27017, type\u003dUNKNOWN, state\u003dCONNECTING, exception\u003d{com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]",
        "isError": true
      },
      {
        "testClass": "ru.vorotov.library.dao.data.DataJpaAuthorRepositoryTest",
        "testMethod": "testGetAll",
        "failureName": "org.springframework.dao.DataAccessResourceFailureException",
        "detail": "Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type\u003dUNKNOWN, servers\u003d[{address\u003dlocalhost:27017, type\u003dUNKNOWN, state\u003dCONNECTING, exception\u003d{com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type\u003dUNKNOWN, servers\u003d[{address\u003dlocalhost:27017, type\u003dUNKNOWN, state\u003dCONNECTING, exception\u003d{com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]",
        "isError": true
      },
      {
        "testClass": "ru.vorotov.library.dao.data.DataJpaAuthorRepositoryTest",
        "testMethod": "testDelete",
        "failureName": "org.springframework.dao.DataAccessResourceFailureException",
        "detail": "Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type\u003dUNKNOWN, servers\u003d[{address\u003dlocalhost:27017, type\u003dUNKNOWN, state\u003dCONNECTING, exception\u003d{com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type\u003dUNKNOWN, servers\u003d[{address\u003dlocalhost:27017, type\u003dUNKNOWN, state\u003dCONNECTING, exception\u003d{com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]",
        "isError": true
      },
      {
        "testClass": "ru.vorotov.library.dao.data.DataJpaGenreRepositoryTest",
        "testMethod": "testGet",
        "failureName": "org.springframework.dao.DataAccessResourceFailureException",
        "detail": "Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type\u003dUNKNOWN, servers\u003d[{address\u003dlocalhost:27017, type\u003dUNKNOWN, state\u003dCONNECTING, exception\u003d{com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type\u003dUNKNOWN, servers\u003d[{address\u003dlocalhost:27017, type\u003dUNKNOWN, state\u003dCONNECTING, exception\u003d{com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]",
        "isError": true
      },
      {
        "testClass": "ru.vorotov.library.dao.data.DataJpaGenreRepositoryTest",
        "testMethod": "testSave",
        "failureName": "org.springframework.dao.DataAccessResourceFailureException",
        "detail": "Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type\u003dUNKNOWN, servers\u003d[{address\u003dlocalhost:27017, type\u003dUNKNOWN, state\u003dCONNECTING, exception\u003d{com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type\u003dUNKNOWN, servers\u003d[{address\u003dlocalhost:27017, type\u003dUNKNOWN, state\u003dCONNECTING, exception\u003d{com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]",
        "isError": true
      }
    ]
  },
  "commits": {
    "buggyBuild": {
      "repoName": "aleksvv/spring-otus",
      "branchName": "HW-mongodatajpa",
      "sha": "ab531214b4df0a08a97afc38b72fc622ae9745bd",
      "url": "http://github.com/aleksvv/spring-otus/commit/ab531214b4df0a08a97afc38b72fc622ae9745bd",
      "date": "Aug 31, 2018 10:28:03 PM"
    }
  },
  "projectMetrics": {
    "numberModules": 2,
    "numberSourceFiles": 42,
    "numberTestFiles": 12,
    "numberLibrariesFailingModule": 82
  },
  "repository": {
    "name": "aleksvv/spring-otus",
    "githubId": 138916504,
    "url": "https://github.com/aleksvv/spring-otus",
    "isFork": false,
    "original": {
      "name": "",
      "githubId": 0,
      "url": ""
    },
    "isPullRequest": false,
    "pullRequestId": 0
  },
  "builds": {
    "buggyBuild": {
      "id": 423184096,
      "url": "http://travis-ci.org/aleksvv/spring-otus/builds/423184096",
      "date": "Aug 31, 2018 10:34:23 PM"
    }
  },
  "reproductionBuggyBuild": {
    "reproductionDateBeginning": "Aug 31, 2018 10:34:37 PM",
    "reproductionDateEnd": "Aug 31, 2018 10:41:25 PM",
    "totalDuration": 404,
    "processDurations": {
      "cloning": {
        "nbSteps": 1,
        "totalDuration": 4,
        "stepNames": [
          "CloneRepository"
        ],
        "stepDurations": [
          4
        ]
      },
      "building": {
        "nbSteps": 2,
        "totalDuration": 25,
        "stepNames": [
          "CheckoutBuggyBuild",
          "BuildProject"
        ],
        "stepDurations": [
          0,
          25
        ]
      },
      "testing": {
        "nbSteps": 1,
        "totalDuration": 350,
        "stepNames": [
          "TestProject"
        ],
        "stepDurations": [
          350
        ]
      }
    },
    "projectRootPomPath": "./workspace/aleksvv/spring-otus/423184096/pom.xml"
  },
  "patchDiff": {
    "files": {
      "numberAdded": 0,
      "numberChanged": 0,
      "numberDeleted": 0
    },
    "lines": {
      "numberAdded": 0,
      "numberDeleted": 0
    }
  },
  "type": "only_fail"
}