{
  "tests": {
    "failingModule": "/root/workspace/traneio/ndbc/428468591/ndbc-postgres-netty4",
    "overallMetrics": {
      "numberRunning": 326,
      "numberPassing": 271,
      "numberFailing": 0,
      "numberErroring": 55,
      "numberSkipping": 3,
      "failures": [
        {
          "failureName": "io.trane.future.CheckedFutureException",
          "isError": true,
          "occurrences": 55
        }
      ]
    },
    "failingClasses": [
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "numberRunning": 30,
        "numberPassing": 0,
        "numberFailing": 0,
        "numberErroring": 30,
        "numberSkipping": 0
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "numberRunning": 14,
        "numberPassing": 0,
        "numberFailing": 0,
        "numberErroring": 14,
        "numberSkipping": 0
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "numberRunning": 11,
        "numberPassing": 0,
        "numberFailing": 0,
        "numberErroring": 11,
        "numberSkipping": 2
      }
    ],
    "failureDetails": [
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "longArray",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleExecuteDeleteFailure",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "integer",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "double_",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "bigDecimalArray",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "float_",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "byte_",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleQuery",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedQueryNoParams",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteUpdateNoParamFailure",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteInsertNoParamFailure",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteDeleteWithParamFailure",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "byteArrayArray",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleExecuteInsertFailure",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "cancellation",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteUpdteWithParamFailure",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleExecuteInsert",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "transactionLocalFailure",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleQueryFailure",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "transactionSuccess",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleExecuteUpdateFailure",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "localTimeArray",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "long_",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedQueryInvalid",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "offsetTime",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "offsetTimeArray",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteUpdateWithParam",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedQueryWithParamsFailure",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleExecuteDelete",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "localTime",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "string",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "short_",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "integerArray",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleQueryInvalid",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "byteArray",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteInsertNoParam",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteInsertWithParamFailure",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleExecuteUpdate",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "localDateTimeArray",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteDeleteNoParamFailure",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "booleanArray",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedQueryNoParamsFailure",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "shortArray",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "_boolean",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteUpdateNoParam",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteDeleteWithParam",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "localDateTime",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "localDate",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "transactionDBFailure",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteDeleteNoParam",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteInsertWithParam",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "doubleArray",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "bigDecimal",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "localDateArray",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedQueryWithParams",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432",
        "isError": true
      }
    ]
  },
  "projectMetrics": {
    "numberModules": 8,
    "numberSourceFiles": 187,
    "numberTestFiles": 70,
    "numberLibrariesFailingModule": 10
  },
  "repository": {
    "name": "traneio/ndbc",
    "githubId": 84398452,
    "url": "https://github.com/traneio/ndbc",
    "isFork": false,
    "original": {
      "name": "",
      "githubId": 0,
      "url": ""
    },
    "isPullRequest": false,
    "pullRequestId": 0
  },
  "builds": {
    "buggyBuild": {
      "id": 428468591,
      "url": "http://travis-ci.org/traneio/ndbc/builds/428468591",
      "date": "Sep 14, 2018 7:05:45 AM"
    }
  },
  "reproductionBuggyBuild": {
    "reproductionDateBeginning": "Sep 14, 2018 7:05:38 AM",
    "reproductionDateEnd": "Sep 14, 2018 7:08:55 AM",
    "totalDuration": 193,
    "processDurations": {
      "cloning": {
        "nbSteps": 1,
        "totalDuration": 3,
        "stepNames": [
          "CloneRepository"
        ],
        "stepDurations": [
          3
        ]
      },
      "building": {
        "nbSteps": 2,
        "totalDuration": 23,
        "stepNames": [
          "CheckoutBuggyBuild",
          "BuildProject"
        ],
        "stepDurations": [
          0,
          23
        ]
      },
      "testing": {
        "nbSteps": 1,
        "totalDuration": 12,
        "stepNames": [
          "TestProject"
        ],
        "stepDurations": [
          12
        ]
      }
    },
    "projectRootPomPath": "./workspace/traneio/ndbc/428468591/pom.xml"
  },
  "patchDiff": {
    "files": {
      "numberAdded": 0,
      "numberChanged": 0,
      "numberDeleted": 0
    },
    "lines": {
      "numberAdded": 0,
      "numberDeleted": 0
    }
  },
  "commits": {
    "buggyBuild": {
      "repoName": "traneio/ndbc",
      "branchName": "master",
      "sha": "a1122ebdb3daf3f2cd27fe13b3cfcf06520e3089",
      "url": "http://github.com/traneio/ndbc/commit/a1122ebdb3daf3f2cd27fe13b3cfcf06520e3089",
      "date": "Sep 14, 2018 7:00:33 AM"
    }
  },
  "type": "only_fail"
}