{
  "repository": {
    "name": "hekate-io/hekate",
    "githubId": 84603051,
    "url": "https://github.com/hekate-io/hekate",
    "isFork": false,
    "original": {
      "name": "",
      "githubId": 0,
      "url": ""
    },
    "isPullRequest": false,
    "pullRequestId": 0
  },
  "builds": {
    "buggyBuild": {
      "id": 418667127,
      "url": "http://travis-ci.org/hekate-io/hekate/builds/418667127",
      "date": "Aug 21, 2018 2:58:19 PM"
    }
  },
  "reproductionBuggyBuild": {
    "reproductionDateBeginning": "Aug 21, 2018 2:58:40 PM",
    "reproductionDateEnd": "Aug 21, 2018 4:11:26 PM",
    "totalDuration": 4363,
    "processDurations": {
      "cloning": {
        "nbSteps": 1,
        "totalDuration": 6,
        "stepNames": [
          "CloneRepository"
        ],
        "stepDurations": [
          6
        ]
      },
      "building": {
        "nbSteps": 2,
        "totalDuration": 207,
        "stepNames": [
          "CheckoutBuggyBuild",
          "BuildProject"
        ],
        "stepDurations": [
          0,
          207
        ]
      },
      "testing": {
        "nbSteps": 1,
        "totalDuration": 2340,
        "stepNames": [
          "TestProject"
        ],
        "stepDurations": [
          2340
        ]
      }
    },
    "projectRootPomPath": "./workspace/hekate-io/hekate/418667127/pom.xml"
  },
  "patchDiff": {
    "files": {
      "numberAdded": 0,
      "numberChanged": 0,
      "numberDeleted": 0
    },
    "lines": {
      "numberAdded": 0,
      "numberDeleted": 0
    }
  },
  "tests": {
    "failingModule": "/root/workspace/hekate-io/hekate/418667127/hekate-core",
    "overallMetrics": {
      "numberRunning": 9385,
      "numberPassing": 9332,
      "numberFailing": 1,
      "numberErroring": 52,
      "numberSkipping": 64,
      "failures": [
        {
          "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
          "isError": true,
          "occurrences": 26
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "isError": true,
          "occurrences": 26
        },
        {
          "failureName": "java.lang.AssertionError",
          "isError": false,
          "occurrences": 1
        }
      ]
    },
    "failingClasses": [
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderCustomTableTest",
        "numberRunning": 39,
        "numberPassing": 13,
        "numberFailing": 0,
        "numberErroring": 26,
        "numberSkipping": 0
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderTest",
        "numberRunning": 39,
        "numberPassing": 13,
        "numberFailing": 0,
        "numberErroring": 26,
        "numberSkipping": 0
      },
      {
        "testClass": "io.hekate.cluster.split.JdbcConnectivityDetectorTest",
        "numberRunning": 6,
        "numberPassing": 5,
        "numberFailing": 1,
        "numberErroring": 0,
        "numberSkipping": 0
      }
    ],
    "failureDetails": [
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderCustomTableTest",
        "testMethod": "testRegisterDuplicate[2:org.postgresql.ds.PGSimpleDataSource@361d169a]",
        "failureName": "org.postgresql.util.PSQLException",
        "detail": "Connection to 127.0.01:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderTest",
        "testMethod": "testStartStopDiscovery[2:org.postgresql.ds.PGSimpleDataSource@b1d7b09]",
        "failureName": "org.postgresql.util.PSQLException",
        "detail": "Connection to 127.0.01:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderTest",
        "testMethod": "testToString[2:org.postgresql.ds.PGSimpleDataSource@b1d7b09]",
        "failureName": "org.postgresql.util.PSQLException",
        "detail": "Connection to 127.0.01:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderTest",
        "testMethod": "testDbErrorOnGetNodes[2:org.postgresql.ds.PGSimpleDataSource@b1d7b09]",
        "failureName": "org.postgresql.util.PSQLException",
        "detail": "Connection to 127.0.01:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderTest",
        "testMethod": "testGetCleanupInterval[2:org.postgresql.ds.PGSimpleDataSource@b1d7b09]",
        "failureName": "org.postgresql.util.PSQLException",
        "detail": "Connection to 127.0.01:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderCustomTableTest",
        "testMethod": "testStartStopDiscovery[1:com.mysql.cj.jdbc.MysqlDataSource@352a8183]",
        "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
        "detail": "Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderTest",
        "testMethod": "testMultipleStopDiscovery[1:com.mysql.cj.jdbc.MysqlDataSource@31ce271c]",
        "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
        "detail": "Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderCustomTableTest",
        "testMethod": "testMultipleStopDiscovery[1:com.mysql.cj.jdbc.MysqlDataSource@352a8183]",
        "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
        "detail": "Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderTest",
        "testMethod": "testUnregisterUnknown[1:com.mysql.cj.jdbc.MysqlDataSource@31ce271c]",
        "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
        "detail": "Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderTest",
        "testMethod": "testDbErrorOnStopDiscovery[1:com.mysql.cj.jdbc.MysqlDataSource@31ce271c]",
        "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
        "detail": "Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderCustomTableTest",
        "testMethod": "testRegisterUnregisterWrongCluster[2:org.postgresql.ds.PGSimpleDataSource@361d169a]",
        "failureName": "org.postgresql.util.PSQLException",
        "detail": "Connection to 127.0.01:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderCustomTableTest",
        "testMethod": "testRegisterUnregisterWrongCluster[1:com.mysql.cj.jdbc.MysqlDataSource@352a8183]",
        "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
        "detail": "Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderCustomTableTest",
        "testMethod": "testDiscovery[1:com.mysql.cj.jdbc.MysqlDataSource@352a8183]",
        "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
        "detail": "Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderCustomTableTest",
        "testMethod": "testToString[1:com.mysql.cj.jdbc.MysqlDataSource@352a8183]",
        "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
        "detail": "Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderTest",
        "testMethod": "testRegisterDuplicate[1:com.mysql.cj.jdbc.MysqlDataSource@31ce271c]",
        "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
        "detail": "Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderCustomTableTest",
        "testMethod": "testDbErrorOnStopDiscovery[2:org.postgresql.ds.PGSimpleDataSource@361d169a]",
        "failureName": "org.postgresql.util.PSQLException",
        "detail": "Connection to 127.0.01:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderTest",
        "testMethod": "testDbErrorOnGetNodes[1:com.mysql.cj.jdbc.MysqlDataSource@31ce271c]",
        "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
        "detail": "Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderTest",
        "testMethod": "testRegisterUnregister[1:com.mysql.cj.jdbc.MysqlDataSource@31ce271c]",
        "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
        "detail": "Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderCustomTableTest",
        "testMethod": "testCleanupWithNodes[1:com.mysql.cj.jdbc.MysqlDataSource@352a8183]",
        "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
        "detail": "Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderTest",
        "testMethod": "testCleanupWithNodes[2:org.postgresql.ds.PGSimpleDataSource@b1d7b09]",
        "failureName": "org.postgresql.util.PSQLException",
        "detail": "Connection to 127.0.01:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderCustomTableTest",
        "testMethod": "testUnregisterUnknown[1:com.mysql.cj.jdbc.MysqlDataSource@352a8183]",
        "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
        "detail": "Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderTest",
        "testMethod": "testRegisterUnregister[2:org.postgresql.ds.PGSimpleDataSource@b1d7b09]",
        "failureName": "org.postgresql.util.PSQLException",
        "detail": "Connection to 127.0.01:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderCustomTableTest",
        "testMethod": "testRegisterUnregister[2:org.postgresql.ds.PGSimpleDataSource@361d169a]",
        "failureName": "org.postgresql.util.PSQLException",
        "detail": "Connection to 127.0.01:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderCustomTableTest",
        "testMethod": "testToString[2:org.postgresql.ds.PGSimpleDataSource@361d169a]",
        "failureName": "org.postgresql.util.PSQLException",
        "detail": "Connection to 127.0.01:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderTest",
        "testMethod": "testRegisterUnregisterWrongCluster[1:com.mysql.cj.jdbc.MysqlDataSource@31ce271c]",
        "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
        "detail": "Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderTest",
        "testMethod": "testDbErrorOnStopDiscovery[2:org.postgresql.ds.PGSimpleDataSource@b1d7b09]",
        "failureName": "org.postgresql.util.PSQLException",
        "detail": "Connection to 127.0.01:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderTest",
        "testMethod": "testToString[1:com.mysql.cj.jdbc.MysqlDataSource@31ce271c]",
        "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
        "detail": "Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderTest",
        "testMethod": "testRegisterDuplicate[2:org.postgresql.ds.PGSimpleDataSource@b1d7b09]",
        "failureName": "org.postgresql.util.PSQLException",
        "detail": "Connection to 127.0.01:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderTest",
        "testMethod": "testRegisterUnregisterWrongCluster[2:org.postgresql.ds.PGSimpleDataSource@b1d7b09]",
        "failureName": "org.postgresql.util.PSQLException",
        "detail": "Connection to 127.0.01:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderCustomTableTest",
        "testMethod": "testRegisterUnregister[1:com.mysql.cj.jdbc.MysqlDataSource@352a8183]",
        "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
        "detail": "Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderCustomTableTest",
        "testMethod": "testCleanupWithNodes[2:org.postgresql.ds.PGSimpleDataSource@361d169a]",
        "failureName": "org.postgresql.util.PSQLException",
        "detail": "Connection to 127.0.01:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderTest",
        "testMethod": "testStartStopDiscovery[1:com.mysql.cj.jdbc.MysqlDataSource@31ce271c]",
        "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
        "detail": "Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderCustomTableTest",
        "testMethod": "testDiscovery[2:org.postgresql.ds.PGSimpleDataSource@361d169a]",
        "failureName": "org.postgresql.util.PSQLException",
        "detail": "Connection to 127.0.01:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderCustomTableTest",
        "testMethod": "testUnregisterUnknown[2:org.postgresql.ds.PGSimpleDataSource@361d169a]",
        "failureName": "org.postgresql.util.PSQLException",
        "detail": "Connection to 127.0.01:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderCustomTableTest",
        "testMethod": "testGetCleanupInterval[1:com.mysql.cj.jdbc.MysqlDataSource@352a8183]",
        "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
        "detail": "Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderTest",
        "testMethod": "testGetCleanupInterval[1:com.mysql.cj.jdbc.MysqlDataSource@31ce271c]",
        "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
        "detail": "Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderCustomTableTest",
        "testMethod": "testDbErrorOnStartDiscovery[1:com.mysql.cj.jdbc.MysqlDataSource@352a8183]",
        "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
        "detail": "Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderCustomTableTest",
        "testMethod": "testRegisterDuplicate[1:com.mysql.cj.jdbc.MysqlDataSource@352a8183]",
        "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
        "detail": "Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderTest",
        "testMethod": "testDiscovery[2:org.postgresql.ds.PGSimpleDataSource@b1d7b09]",
        "failureName": "org.postgresql.util.PSQLException",
        "detail": "Connection to 127.0.01:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderCustomTableTest",
        "testMethod": "testDbErrorOnGetNodes[2:org.postgresql.ds.PGSimpleDataSource@361d169a]",
        "failureName": "org.postgresql.util.PSQLException",
        "detail": "Connection to 127.0.01:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderCustomTableTest",
        "testMethod": "testDbErrorOnStopDiscovery[1:com.mysql.cj.jdbc.MysqlDataSource@352a8183]",
        "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
        "detail": "Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderCustomTableTest",
        "testMethod": "testStartStopDiscovery[2:org.postgresql.ds.PGSimpleDataSource@361d169a]",
        "failureName": "org.postgresql.util.PSQLException",
        "detail": "Connection to 127.0.01:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderTest",
        "testMethod": "testDiscovery[1:com.mysql.cj.jdbc.MysqlDataSource@31ce271c]",
        "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
        "detail": "Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderCustomTableTest",
        "testMethod": "testGetCleanupInterval[2:org.postgresql.ds.PGSimpleDataSource@361d169a]",
        "failureName": "org.postgresql.util.PSQLException",
        "detail": "Connection to 127.0.01:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderCustomTableTest",
        "testMethod": "testDbErrorOnStartDiscovery[2:org.postgresql.ds.PGSimpleDataSource@361d169a]",
        "failureName": "org.postgresql.util.PSQLException",
        "detail": "Connection to 127.0.01:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderTest",
        "testMethod": "testMultipleStopDiscovery[2:org.postgresql.ds.PGSimpleDataSource@b1d7b09]",
        "failureName": "org.postgresql.util.PSQLException",
        "detail": "Connection to 127.0.01:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderTest",
        "testMethod": "testDbErrorOnStartDiscovery[2:org.postgresql.ds.PGSimpleDataSource@b1d7b09]",
        "failureName": "org.postgresql.util.PSQLException",
        "detail": "Connection to 127.0.01:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderTest",
        "testMethod": "testCleanupWithNodes[1:com.mysql.cj.jdbc.MysqlDataSource@31ce271c]",
        "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
        "detail": "Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderTest",
        "testMethod": "testDbErrorOnStartDiscovery[1:com.mysql.cj.jdbc.MysqlDataSource@31ce271c]",
        "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
        "detail": "Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderCustomTableTest",
        "testMethod": "testDbErrorOnGetNodes[1:com.mysql.cj.jdbc.MysqlDataSource@352a8183]",
        "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
        "detail": "Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.split.JdbcConnectivityDetectorTest",
        "testMethod": "testRealDataSources",
        "failureName": "java.lang.AssertionError",
        "detail": "com.mysql.cj.jdbc.MysqlDataSource@43365722",
        "isError": false
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderTest",
        "testMethod": "testUnregisterUnknown[2:org.postgresql.ds.PGSimpleDataSource@b1d7b09]",
        "failureName": "org.postgresql.util.PSQLException",
        "detail": "Connection to 127.0.01:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
        "isError": true
      },
      {
        "testClass": "io.hekate.cluster.seed.jdbc.JdbcSeedNodeProviderCustomTableTest",
        "testMethod": "testMultipleStopDiscovery[2:org.postgresql.ds.PGSimpleDataSource@361d169a]",
        "failureName": "org.postgresql.util.PSQLException",
        "detail": "Connection to 127.0.01:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
        "isError": true
      }
    ]
  },
  "commits": {
    "buggyBuild": {
      "repoName": "hekate-io/hekate",
      "branchName": "dev",
      "sha": "906e57f9987f10895f65566eba32c67e3acf206d",
      "url": "http://github.com/hekate-io/hekate/commit/906e57f9987f10895f65566eba32c67e3acf206d",
      "date": "Aug 21, 2018 2:09:21 PM"
    }
  },
  "projectMetrics": {
    "numberModules": 14,
    "numberSourceFiles": 656,
    "numberTestFiles": 354,
    "numberLibrariesFailingModule": 29
  },
  "type": "only_fail"
}