{
  "repository": {
    "name": "Texera/texera",
    "githubId": 53976910,
    "url": "https://github.com/Texera/texera",
    "isFork": false,
    "original": {
      "name": "",
      "githubId": 0,
      "url": ""
    },
    "isPullRequest": false,
    "pullRequestId": 0
  },
  "builds": {
    "buggyBuild": {
      "id": 413822400,
      "url": "http://travis-ci.org/Texera/texera/builds/413822400",
      "date": "Aug 9, 2018 12:59:30 AM"
    }
  },
  "reproductionBuggyBuild": {
    "reproductionDateBeginning": "Aug 9, 2018 1:03:09 AM",
    "reproductionDateEnd": "Aug 9, 2018 1:14:49 AM",
    "totalDuration": 697,
    "processDurations": {
      "cloning": {
        "nbSteps": 1,
        "totalDuration": 16,
        "stepNames": [
          "CloneRepository"
        ],
        "stepDurations": [
          16
        ]
      },
      "building": {
        "nbSteps": 2,
        "totalDuration": 104,
        "stepNames": [
          "CheckoutBuggyBuild",
          "BuildProject"
        ],
        "stepDurations": [
          0,
          104
        ]
      },
      "testing": {
        "nbSteps": 1,
        "totalDuration": 265,
        "stepNames": [
          "TestProject"
        ],
        "stepDurations": [
          265
        ]
      }
    },
    "projectRootPomPath": "./workspace/Texera/texera/413822400/core/pom.xml"
  },
  "patchDiff": {
    "files": {
      "numberAdded": 0,
      "numberChanged": 0,
      "numberDeleted": 0
    },
    "lines": {
      "numberAdded": 0,
      "numberDeleted": 0
    }
  },
  "tests": {
    "failingModule": "/root/workspace/Texera/texera/413822400/core/dataflow",
    "overallMetrics": {
      "numberRunning": 350,
      "numberPassing": 342,
      "numberFailing": 0,
      "numberErroring": 8,
      "numberSkipping": 0,
      "failures": [
        {
          "failureName": "edu.uci.ics.texera.api.exception.DataflowException",
          "isError": true,
          "occurrences": 8
        }
      ]
    },
    "failingClasses": [
      {
        "testClass": "edu.uci.ics.texera.dataflow.nlp.sentiment.NltkSentimentOperatorTest",
        "numberRunning": 3,
        "numberPassing": 0,
        "numberFailing": 0,
        "numberErroring": 3,
        "numberSkipping": 0
      },
      {
        "testClass": "edu.uci.ics.texera.dataflow.resource.dictionary.DictionaryManagerTest",
        "numberRunning": 5,
        "numberPassing": 0,
        "numberFailing": 0,
        "numberErroring": 5,
        "numberSkipping": 0
      }
    ],
    "failureDetails": [
      {
        "testClass": "edu.uci.ics.texera.dataflow.nlp.sentiment.NltkSentimentOperatorTest",
        "testMethod": "test1",
        "failureName": "edu.uci.ics.texera.api.exception.DataflowException",
        "detail": "Cannot run program \"python3\": error\u003d2, No such file or directory",
        "isError": true
      },
      {
        "testClass": "edu.uci.ics.texera.dataflow.resource.dictionary.DictionaryManagerTest",
        "testMethod": "getDictionariesTest",
        "failureName": "edu.uci.ics.texera.api.exception.DataflowException",
        "detail": "DictionaryManager failed to connect to mysql database.Could not create connection to database server. Attempted reconnect 3 times. Giving up.",
        "isError": true
      },
      {
        "testClass": "edu.uci.ics.texera.dataflow.resource.dictionary.DictionaryManagerTest",
        "testMethod": "addDictionaryTest",
        "failureName": "edu.uci.ics.texera.api.exception.DataflowException",
        "detail": "DictionaryManager failed to connect to mysql database.Could not create connection to database server. Attempted reconnect 3 times. Giving up.",
        "isError": true
      },
      {
        "testClass": "edu.uci.ics.texera.dataflow.nlp.sentiment.NltkSentimentOperatorTest",
        "testMethod": "test3",
        "failureName": "edu.uci.ics.texera.api.exception.DataflowException",
        "detail": "Cannot run program \"python3\": error\u003d2, No such file or directory",
        "isError": true
      },
      {
        "testClass": "edu.uci.ics.texera.dataflow.resource.dictionary.DictionaryManagerTest",
        "testMethod": "connectionTest",
        "failureName": "edu.uci.ics.texera.api.exception.DataflowException",
        "detail": "DictionaryManager failed to connect to mysql database.Could not create connection to database server. Attempted reconnect 3 times. Giving up.",
        "isError": true
      },
      {
        "testClass": "edu.uci.ics.texera.dataflow.resource.dictionary.DictionaryManagerTest",
        "testMethod": "getDictionaryTest",
        "failureName": "edu.uci.ics.texera.api.exception.DataflowException",
        "detail": "DictionaryManager failed to connect to mysql database.Could not create connection to database server. Attempted reconnect 3 times. Giving up.",
        "isError": true
      },
      {
        "testClass": "edu.uci.ics.texera.dataflow.resource.dictionary.DictionaryManagerTest",
        "testMethod": "destroyDictionaryManagerTest",
        "failureName": "edu.uci.ics.texera.api.exception.DataflowException",
        "detail": "DictionaryManager failed to connect to mysql database.Could not create connection to database server. Attempted reconnect 3 times. Giving up.",
        "isError": true
      },
      {
        "testClass": "edu.uci.ics.texera.dataflow.nlp.sentiment.NltkSentimentOperatorTest",
        "testMethod": "test2",
        "failureName": "edu.uci.ics.texera.api.exception.DataflowException",
        "detail": "Cannot run program \"python3\": error\u003d2, No such file or directory",
        "isError": true
      }
    ]
  },
  "commits": {
    "buggyBuild": {
      "repoName": "Texera/texera",
      "branchName": "oliver-daemonDB",
      "sha": "aef6a172e01eca85d251395dd73e34e45e4dd252",
      "url": "http://github.com/Texera/texera/commit/aef6a172e01eca85d251395dd73e34e45e4dd252",
      "date": "Aug 9, 2018 12:50:37 AM"
    }
  },
  "projectMetrics": {
    "numberModules": 7,
    "numberSourceFiles": 205,
    "numberTestFiles": 79,
    "numberLibrariesFailingModule": 141
  },
  "type": "only_fail"
}