15:49:14,285  INFO DefaultTestContextBootstrapper:174 - Using TestExecutionListeners: [org.springframework.test.context.web.ServletTestExecutionListener@715f45c6, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener@5d5c41e5, org.springframework.test.context.support.DependencyInjectionTestExecutionListener@43245559, org.springframework.test.context.support.DirtiesContextTestExecutionListener@42e4e589]
15:49:14,295  INFO DefaultLoadEventListener:159 - HHH000327: Error performing load command : org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [org.sakaiproject.tool.assessment.data.dao.assessment.PublishedAssessmentData#999999]
15:49:14,295  WARN PublishedAssessmentFacadeQueries:901 - Error accessing Published Assesment: 999999 storage returned: org.springframework.orm.hibernate4.HibernateObjectRetrievalFailureException: No row with the given identifier exists: [org.sakaiproject.tool.assessment.data.dao.assessment.PublishedAssessmentData#999999]; nested exception is org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [org.sakaiproject.tool.assessment.data.dao.assessment.PublishedAssessmentData#999999]
