<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="cyclone1" name="com.h3xstream.findsecbugs.xss.JspXssFsaDetectorTest" tests="1" failures="1" timestamp="5 Jun 2018 22:04:41 GMT" time="0.732" errors="0">
  <testcase name="test" time="0.732" classname="com.h3xstream.findsecbugs.xss.JspXssFsaDetectorTest">
    <failure type="org.mockito.exceptions.verification.NeverWantedButInvoked" message="
securityReporter.doReportBug(
    BugInstance with:
bugType=&quot;XSS_JSP_PRINT&quot;,
);
Never wanted here:
-&gt; at com.h3xstream.findsecbugs.xss.JspXssFsaDetectorTest.test(JspXssFsaDetectorTest.java:65)
But invoked here:
-&gt; at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)
">
      <![CDATA[org.mockito.exceptions.verification.NeverWantedButInvoked: 
securityReporter.doReportBug(
    BugInstance with:
bugType="XSS_JSP_PRINT",
);
Never wanted here:
-> at com.h3xstream.findsecbugs.xss.JspXssFsaDetectorTest.test(JspXssFsaDetectorTest.java:65)
But invoked here:
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)

	at com.h3xstream.findsecbugs.xss.JspXssFsaDetectorTest.test(JspXssFsaDetectorTest.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
    </failure>
  </testcase> <!-- test -->
</testsuite> <!-- com.h3xstream.findsecbugs.xss.JspXssFsaDetectorTest -->
