-------------------------------------------------------------------------------
Test set: redis.clients.jedis.tests.SSLJedisTest
-------------------------------------------------------------------------------
Tests run: 8, Failures: 3, Errors: 5, Skipped: 0, Time elapsed: 0.248 sec <<< FAILURE! - in redis.clients.jedis.tests.SSLJedisTest
connectWithUrl(redis.clients.jedis.tests.SSLJedisTest)  Time elapsed: 0 sec  <<< ERROR!
redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6390
	at redis.clients.jedis.tests.SSLJedisTest.connectWithUrl(SSLJedisTest.java:57)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at redis.clients.jedis.tests.SSLJedisTest.connectWithUrl(SSLJedisTest.java:57)

connectWithoutShardInfo(redis.clients.jedis.tests.SSLJedisTest)  Time elapsed: 0 sec  <<< ERROR!
redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6390
	at redis.clients.jedis.tests.SSLJedisTest.connectWithoutShardInfo(SSLJedisTest.java:69)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at redis.clients.jedis.tests.SSLJedisTest.connectWithoutShardInfo(SSLJedisTest.java:69)

connectWithShardInfoAndCustomHostnameVerifierByIpAddress(redis.clients.jedis.tests.SSLJedisTest)  Time elapsed: 0.233 sec  <<< FAILURE!
org.junit.ComparisonFailure: The JedisConnectionException does not contain the expected message. expected:<[The connection to '127.0.0.1' failed ssl/tls hostname verification.]> but was:<[Failed connecting to host 127.0.0.1:6390]>
	at redis.clients.jedis.tests.SSLJedisTest.connectWithShardInfoAndCustomHostnameVerifierByIpAddress(SSLJedisTest.java:200)

connectWithShardInfoByIpAddress(redis.clients.jedis.tests.SSLJedisTest)  Time elapsed: 0.008 sec  <<< FAILURE!
java.lang.AssertionError: Unexpected first inner exception. expected:<class javax.net.ssl.SSLHandshakeException> but was:<class java.net.ConnectException>
	at redis.clients.jedis.tests.SSLJedisTest.connectWithShardInfoByIpAddress(SSLJedisTest.java:127)

connectWithShardInfo(redis.clients.jedis.tests.SSLJedisTest)  Time elapsed: 0 sec  <<< ERROR!
redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6390
	at redis.clients.jedis.tests.SSLJedisTest.connectWithShardInfo(SSLJedisTest.java:94)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at redis.clients.jedis.tests.SSLJedisTest.connectWithShardInfo(SSLJedisTest.java:94)

connectWithShardInfoAndEmptyTrustStore(redis.clients.jedis.tests.SSLJedisTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError: Unexpected first inner exception. expected:<class javax.net.ssl.SSLException> but was:<class java.net.ConnectException>
	at redis.clients.jedis.tests.SSLJedisTest.connectWithShardInfoAndEmptyTrustStore(SSLJedisTest.java:232)

connectWithShardInfoAndCustomHostnameVerifier(redis.clients.jedis.tests.SSLJedisTest)  Time elapsed: 0.001 sec  <<< ERROR!
redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6390
	at redis.clients.jedis.tests.SSLJedisTest.connectWithShardInfoAndCustomHostnameVerifier(SSLJedisTest.java:155)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at redis.clients.jedis.tests.SSLJedisTest.connectWithShardInfoAndCustomHostnameVerifier(SSLJedisTest.java:155)

connectWithShardInfoAndCustomSocketFactory(redis.clients.jedis.tests.SSLJedisTest)  Time elapsed: 0.003 sec  <<< ERROR!
redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6390
	at redis.clients.jedis.tests.SSLJedisTest.connectWithShardInfoAndCustomSocketFactory(SSLJedisTest.java:174)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at redis.clients.jedis.tests.SSLJedisTest.connectWithShardInfoAndCustomSocketFactory(SSLJedisTest.java:174)

