-------------------------------------------------------------------------------
Test set: redis.clients.jedis.tests.ConnectionTest
-------------------------------------------------------------------------------
Tests run: 5, Failures: 1, Errors: 2, Skipped: 0, Time elapsed: 0.015 sec <<< FAILURE! - in redis.clients.jedis.tests.ConnectionTest
connectIfNotConnectedWhenSettingTimeoutInfinite(redis.clients.jedis.tests.ConnectionTest)  Time elapsed: 0 sec  <<< ERROR!
redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6379
	at redis.clients.jedis.tests.ConnectionTest.connectIfNotConnectedWhenSettingTimeoutInfinite(ConnectionTest.java:45)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at redis.clients.jedis.tests.ConnectionTest.connectIfNotConnectedWhenSettingTimeoutInfinite(ConnectionTest.java:45)

getErrorAfterConnectionReset(redis.clients.jedis.tests.ConnectionTest)  Time elapsed: 0.014 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[ERR Protocol error: invalid multibulk length]> but was:<[Failed connecting to host localhost:6379]>
	at redis.clients.jedis.tests.ConnectionTest.getErrorAfterConnectionReset(ConnectionTest.java:75)

checkCloseable(redis.clients.jedis.tests.ConnectionTest)  Time elapsed: 0 sec  <<< ERROR!
redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6379
	at redis.clients.jedis.tests.ConnectionTest.checkCloseable(ConnectionTest.java:52)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at redis.clients.jedis.tests.ConnectionTest.checkCloseable(ConnectionTest.java:52)

