-------------------------------------------------------------------------------
Test set: com.oneandone.ejbcdiunit.mvcc.MvccTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 27.534 sec <<< FAILURE! - in com.oneandone.ejbcdiunit.mvcc.MvccTest
testH2(com.oneandone.ejbcdiunit.mvcc.MvccTest)  Time elapsed: 0.336 sec
testMariaDb(com.oneandone.ejbcdiunit.mvcc.MvccTest)  Time elapsed: 27.113 sec  <<< ERROR!
ch.vorburger.exec.ManagedProcessException: An error occurred while starting the database
	at com.oneandone.ejbcdiunit.mvcc.MvccTest.createConnection(MvccTest.java:62)
	at com.oneandone.ejbcdiunit.mvcc.MvccTest.initDb(MvccTest.java:77)
	at com.oneandone.ejbcdiunit.mvcc.MvccTest.testMariaDb(MvccTest.java:133)
Caused by: ch.vorburger.exec.ManagedProcessException: 
Asked to wait for "mysqld: ready for connections." from Program [/tmp/MariaDB4j/base/bin/mysqld, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir=/tmp/MariaDB4j/base, --datadir=/tmp/MariaDB4j/data/3406, --port=3406, --socket=/tmp/MariaDB4j.3406.sock] (in working directory /tmp/MariaDB4j/base), but it already exited! (without that message in console), last 100 lines of console:
2018-06-07 14:38:58 140679082727296 [Note] /tmp/MariaDB4j/base/bin/mysqld (mysqld 10.1.13-MariaDB) starting as process 6366 ...
2018-06-07 14:38:58 140679082727296 [ERROR] Fatal error: Please consult the Knowledge Base to find out how to run mysqld as root!

2018-06-07 14:38:58 140679082727296 [ERROR] Aborting

	at com.oneandone.ejbcdiunit.mvcc.MvccTest.createConnection(MvccTest.java:62)
	at com.oneandone.ejbcdiunit.mvcc.MvccTest.initDb(MvccTest.java:77)
	at com.oneandone.ejbcdiunit.mvcc.MvccTest.testMariaDb(MvccTest.java:133)

